services:
  db:
    image: jvboronatjosep/sqldiscos:v2
    container_name: contenedorDiscosSql
    ports:
      - "3306:3306"
  php:
    image: jvboronatjosep/phpdiscos:v2
    container_name: contenedorDiscosPhp
    ports:
      - "8080:80"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8081:80"
    depends_on:
      - db